---
Name: "ipmi/configure/key"
Description: "The Key for the certificate to install on this system's BMC"
Documentation: |
  The Key for the certificate to install on this system's BMC
Schema:
  type: "string"
Meta:
  icon: "address card outline"
  color: "blue"
  title: "RackN Content"
  render: "link"
