---
Name: "ipmi/configure/password"
Description: "Password to create on the BMC for the configured user"
Documentation: |
  Password to create on the BMC for the configured user.
Secure: true
Schema:
  type: "string"
  default: "cr0wBar!"
Meta:
  icon: "server"
  color: "blue"
  title: "RackN Content"
