---
Name: "ipmi/configure/cert-country"
Description: "The Country part of the CSR"
Documentation: |
  The Country part of the CSR
Schema:
  type: "string"
  default: US
Meta:
  icon: "address card outline"
  color: "blue"
  title: "RackN Content"
  render: "link"
