---
Name: "ipmi/configure/certificate"
Description: "The certificate to install on the BMC"
Documentation: |
  The Certificate Signing Request for this system's BMC
Schema:
  type: "string"
Meta:
  icon: "address card outline"
  color: "blue"
  title: "RackN Content"
  render: "link"
