---
Name: "ipmi/configure/generate-random-password"
Description: "Should the system generate a random password for the ipmi/password parameter"
Documentation: |
  ipmi/generate-random-password when set to true, the system will be build a random password for
  the system and will ignore the ipmi/configure/password.

  The parameter, ipmi/random-password-settings, will be used to scope the password generation
  process.
Schema:
  type: "boolean"
  default: false
Meta:
  icon: "server"
  color: "blue"
  title: "RackN Content"
