---
Name: "ipmi/configure/ntp-server"
Description: "NTP Server for the BMC to use"
Documentation: |
  NTP Server for the BMC to use
Schema:
  type: "string"
Meta:
  icon: "server"
  color: "blue"
  title: "RackN Content"
