---
Name: "ipmi/configure/cert-locality"
Description: "The Locality part of the CSR"
Documentation: |
  The Locality part of the CSR
Schema:
  type: "string"
  default: Austin
Meta:
  icon: "address card outline"
  color: "blue"
  title: "RackN Content"
  render: "link"
