---
Name: "ipmi/configure/cert-province"
Description: "The Province part of the CSR"
Documentation: |
  The Province part of the CSR
Schema:
  type: "string"
  default: Texas
Meta:
  icon: "address card outline"
  color: "blue"
  title: "RackN Content"
  render: "link"
