---
Name: "ipmi/configure/cert-org"
Description: "The Organization part of the CSR"
Documentation: |
  The Organization part of the CSR
Schema:
  type: "string"
  default: RackN
Meta:
  icon: "address card outline"
  color: "blue"
  title: "RackN Content"
  render: "link"
