language: go
go:
- '1.13'
git:
  depth: 500
sudo: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
- "./tools/build.sh"
script:
- "./tools/test.sh"
- "./tools/build_rel_notes.sh"
- "./tools/publish.sh"
after_script:
- tools/notify.sh digitalrebar/provision-plugins
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
env:
  global:
  - secure: uKct013piqLk5OTiliVXfOD7cXwfHvcm9aWhc/oK6mVdllyB4scGJX6FoB/Gx6roGLVncoUtrQcf8lnmrT3XS/Rqr2UQABaj3bCZg1r9jKxpgvC8zzM9HanrH07QjiQ1ervuzBnI+NhMgCHCECHPp0cr8Fn24SkWxF60LKTsxAXlpB1lQdNgBnehtZurfIRFVaDWQ1Y38lLmKt4T6ex9nEMPrnJIYbBAd0ah71zqs4aUZ7BiK3rnag8hj7BcCIHfweAF5zNlgFzEAz6h35PSdYXESNFRL8U3td6/dIHXX0ludO2tkAvLR99MecCVQeLrEshZS7tkyGyxnK46of/Ei8bCOQBzP2yyITCI2nWU6nYRJaTYcAoUx4Bg4QDYvUQRHEJ4L3EXv4Kj10GvbAtWhRW/xHwGEz3Uq0U39ymt+eT86m1+1Ag4kGnIqOyUWsmbMG7vafhBiV8xlvuTHgBLNCc7mfzja9Hq43ByeQANTDEdZW2R9UPW4tai5LVIV56RXgr3zXd0QNxmvagnqytVhmzO0BQBDr2C+AJTT2lw8qSeDk6T7xJtg5oqEAWGaeaCoWZA3XytYU01nfHKR5JnYJmER97RzlIY4MNJ2qM2iJpqe1/yp2mdJUyT0HnnFNJN684ANqhvvm7cEcFVwmWHuksWV7UdTnf4anLjUU7hyBY=
  - secure: oBJ141yWlgT2XtxNrdOElR33o1ugbWqzGDaSwEtsC55MVY5+UeYYcSvmayrd0VZrZDDDOdQjCHlsQCsURBNhG1DGYc1x2meVCcCBtXynrgbmjAFwInam4XewwviBJUqX2RsFDcJbr8EwVFQsNQOEOjZ7Kj3EgBFMIjNAut7mOvp9Do9dda+KYNEi7d4JMeLoHSySb9hbPhXbtJ5nQB97+apuNEOkAcVjnRMWcHRpsQZgbJUO2MUeqbG3eZiHqmLNSUW0Hk2HAAOv4Su0bAD74hcg4crNKus/SBcoe1HfnKu1povJ7yDwJ6tTa411SOoaWL/iOfplYZKUiKx2pdH4SWb02h4bAA4ucwHXOk783Coz04M2nAaZKcq+jqFPgfSIAtgnscDczLrdmpiIpNy6XgOXrGOJloE/l3gN2o9gBr+YzmAAEfE85VStabAAoKzouSHQXB9JClqgudX9MRzfm3VT3BvX4BJLXG8EDH3arfCe4z8ckivy1YKow9E90TQt7FGJhCLv7ztFhCToKREvv9u9PcG7NZgGCFM96Xj5MhA0CeojC7KKIqGxeoY4OhJofG4YX8tyJPCEI6QRxqQUv+3WUu0lkupyXd+gJ/I2KwaYjTO/jiLfBsYp/2XRw2J+fOOperrBVtDZCSHF5LAYovz6nR2n3YgguoXFGiWLBgA=
  - secure: Dcvd5F5WUJ5PkmMu/RWHZ4NxuBRKvKcLQCXelfxSlkRPqD6EcNqN9XtiueQmEwM/fYrxYGQBnaeeGS2nJzcdKlBBJrmaHGZwB3d6Aklz2A1Of/NDSkWNc1UqmZjjXHLCOQIvm3P/SbA3r+o9x9L4KFM1LSBoMGNqb64Xp2rE843tnehzP2G5qccfSChZ3yBj4OYXZOdE7nC7v95c4r5sMURCp8t6ZF23EBpy10A1zZ2OTBYo8l7SVB+3k//iPnPaUAivkumbJt+RC5v0v5Wkk4QRsA/coJjA5YMOFHStxpN4pWVhE7vgveqvDzyqzrQoTjz0WNtbM0Tngv+pzVHFzdWGH0NiinaIAxagFRNLnqYIIURyYlgn5YD+RiMYdgY+sH3lCpEGFI0lSA7cvGtBqjDcdzwP6JQ7G0gjrBkZFlIAYghG/qimumY4mLxeDogYmUKZwH7nP0t+RiOCTYemH30oHZmIlCX7Ywx5O8ke0LA06XxPFCJsOpzx3aWQvWAXJZ4dEH4Bg8bLZ8ASlHf6Rrf9aJnA5FLdwI4KDBBur0WbMP7QA0CuiRkhnPDWRCe1RpO7vLV8GsUf9QRKl5Lrs2lltALMEKBwIaFVVbYZviZsW+tVjg3dwnd8GUsl5nh27KrRCleu71GkHkYOGW23BedUofnrAoA3Ix4J/aOCbOs=
deploy:
- provider: s3
  access_key_id: AKIAJY25W4N3CA7NRHJQ
  secret_access_key:
    secure: sFgGfGS54LxyrMyP416XL/KhBw5oIfYG3A3pCDrCNGNveknzItR8hywuY0i06Ac/SFOLQUhlNTxzpHtIoCTi6dDZM/EUWo+5DJ15doU42CY++TwEATQrnN8w3JQIDng9IW3loY7h76pi999PMX4VKOBxNwcMp7n441s0eQ/Y4tBIgNIgkLHJesWxrf72eUbn0FdSoJ2H/U6/WZOzfJt7nwsswKzZ+le1RRanIXPRgYulmzo94G1S6jkKhq03lvvtem2QbkbPZGbnKPcrKrXZTF+Xx8Nr8pkr2OnFJTeHt0IMLP/Ub14KkV/xrFxsQzsa2axkjkLgtBeu7MOQzcOqGJg0mmHOjs6Pyrn8CvlDU2AqNwmfsTGGBKkOmngY6zwr02W9Mi9yQDY1Ri84nQ/gXtyP1SxJS9K72TCKjVIaN7DifQu/vajoIZwcYZ2n6KjEkNzj5i18RDVW0zTQWO/pU7JolgII/Vp+fWrMdvGu0m5/uFjjWC5fFCZRBoRfhw1sWvT+Y7MDQfsvkJJ86a6k3YSqxuirsndvy5FfskgqDJgrOK0AKcdMnloyTQOY6CE2t6mwRI1JpThHtaUq0gSZqsIVTjamW9cWg6QhlRe59bZFTu0YJi8NJKct49dHsQZOvs17AUZzyaiT9WZhxTME36KhCWMfT5TPNY+atUE52zQ=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    branch: v4
- provider: s3
  access_key_id: AKIAJY25W4N3CA7NRHJQ
  secret_access_key:
    secure: sFgGfGS54LxyrMyP416XL/KhBw5oIfYG3A3pCDrCNGNveknzItR8hywuY0i06Ac/SFOLQUhlNTxzpHtIoCTi6dDZM/EUWo+5DJ15doU42CY++TwEATQrnN8w3JQIDng9IW3loY7h76pi999PMX4VKOBxNwcMp7n441s0eQ/Y4tBIgNIgkLHJesWxrf72eUbn0FdSoJ2H/U6/WZOzfJt7nwsswKzZ+le1RRanIXPRgYulmzo94G1S6jkKhq03lvvtem2QbkbPZGbnKPcrKrXZTF+Xx8Nr8pkr2OnFJTeHt0IMLP/Ub14KkV/xrFxsQzsa2axkjkLgtBeu7MOQzcOqGJg0mmHOjs6Pyrn8CvlDU2AqNwmfsTGGBKkOmngY6zwr02W9Mi9yQDY1Ri84nQ/gXtyP1SxJS9K72TCKjVIaN7DifQu/vajoIZwcYZ2n6KjEkNzj5i18RDVW0zTQWO/pU7JolgII/Vp+fWrMdvGu0m5/uFjjWC5fFCZRBoRfhw1sWvT+Y7MDQfsvkJJ86a6k3YSqxuirsndvy5FfskgqDJgrOK0AKcdMnloyTQOY6CE2t6mwRI1JpThHtaUq0gSZqsIVTjamW9cWg6QhlRe59bZFTu0YJi8NJKct49dHsQZOvs17AUZzyaiT9WZhxTME36KhCWMfT5TPNY+atUE52zQ=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    tags: true
