language: go
go:
- '1.12'
git:
  depth: 500
sudo: false
install:
- "./tools/build.sh"
script:
- "./tools/test.sh"
- "./tools/publish.sh"
after_script:
- tools/notify.sh digitalrebar/provision-plugins
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
env:
  global:
    secure: rJ6QnC/zvxOo17WwH7r1oN2y00iJiF+O/QrzRZpU3pD/NQbPIoD7uCvZ/jlz5m5HQR9CsiNovi/Da9Fw0dty8LoE5cw3PfNdpNoNbii0ZE7xwCWmVAImZEyHLYSJTbEXgIlQuHo5jxlK5SyotElaRF8Eq3u+4FeWFCvgB6J3CZVxlUwbWCcY8vp7qSrP/jtw7QYX9n95BpcR4flpApgArMBTD1xF4SsIboJKztHe6DuDPcFSLnA2RNmIxZBl8UfVhWcwIx6R5ff9VH749Na8x2IBCxT8r/lTC7NkQ/MXTlWd0yNGv5rDIqq1Sfgie2PYLczyIWvGb7GzHzJT/6ZIsChe/dSFEriKdXGXi4M0mF3FVxDKAuT5iW5o2tL08jmXhCEsvOYmUy+l6I3Me6qNs4zDNWUYbXWltYEqDKGoI7+eZV/SkVYCdDFvRZjzbQNLbCtbXlR3nWLV2quC1vVdYEVm9WOHPydaCjRKOZ1ugorqTmIv4uGCaucPA7FREbe6k9JY0tZsYVE25fYqWMJmKbviDQKy/oInMG0U/QsAeuVOl+f+JqBKrN1sFFPYjWvsCF6ZNRZU6P4qoVOTw2Nf6EKPwXXAH3IC0PeQa5s9mDSle6wU9pQPEeuliBzU5KxCMdchFnP6Q5JOyNsA3Pj4Cgg6g+umeVmy6qtf8CvXjIE=
deploy:
- provider: s3
  access_key_id: AKIAJ34357Y4ZWJR322Q
  secret_access_key:
    secure: RnUoccWwAo80535t+40GHdgGqGsgdt/fgjAh+75n/6DfS4EkubYvltUFdk//smyE/mEcowX8fCkA7hMT+qDqT+wXwS+kxzIbnBh6wf3g6CJZWGb3E/UG/d3fMalfKQ2pAU4thwEa21wTSHl9FtJGZcICeoKrOvkT78KxSrHH5PIyCsKFFXLqs5JNfN5vND7daT/XhLPyCgpzeX3G2CG3O04HpQlNIcWNDWoGzfYaOoZoQderpxL64Ow0ilSjZoOaM10ySZSlS4K42uUZouOknqrh564sL3ooIoI5FYp0et3dl2r+dIvpHsLcvgA+Mdmk/2tfYKB1fVGRw1AA9Phhx6tuH3RGUnfRXgeF2LFAjgkrqi/D+jEXCXAnTkHTAlKZcf2uY22CkkM31t8OdTx0BPQLiipaKE7fWDeEJFfVUzJ4Mty8eV6hfSicaWnjkv7HGprxWi+mOW4ghbKGMrzRGUCcY2rdLeO1kltrDdA70BlHPrDpkcO92xDttV733fuPfU3eYGlNt7FMpXqdYkGk3OwLS+bslcuvhgUVCpPS9B3tbT5W8a4GEIIw94djpD1UiIePp8BJGSFnVjGeSiFYq42rW6rgY8UQs+dkYVAH4wRVhiRSt+2WGfWydYbSf4mwGMg+B28rY2T1XFmnttNB8i3BMTrGsXWkg2HuntX2lCg=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    branch: v4
- provider: s3
  access_key_id: AKIAJ34357Y4ZWJR322Q
  secret_access_key:
    secure: RnUoccWwAo80535t+40GHdgGqGsgdt/fgjAh+75n/6DfS4EkubYvltUFdk//smyE/mEcowX8fCkA7hMT+qDqT+wXwS+kxzIbnBh6wf3g6CJZWGb3E/UG/d3fMalfKQ2pAU4thwEa21wTSHl9FtJGZcICeoKrOvkT78KxSrHH5PIyCsKFFXLqs5JNfN5vND7daT/XhLPyCgpzeX3G2CG3O04HpQlNIcWNDWoGzfYaOoZoQderpxL64Ow0ilSjZoOaM10ySZSlS4K42uUZouOknqrh564sL3ooIoI5FYp0et3dl2r+dIvpHsLcvgA+Mdmk/2tfYKB1fVGRw1AA9Phhx6tuH3RGUnfRXgeF2LFAjgkrqi/D+jEXCXAnTkHTAlKZcf2uY22CkkM31t8OdTx0BPQLiipaKE7fWDeEJFfVUzJ4Mty8eV6hfSicaWnjkv7HGprxWi+mOW4ghbKGMrzRGUCcY2rdLeO1kltrDdA70BlHPrDpkcO92xDttV733fuPfU3eYGlNt7FMpXqdYkGk3OwLS+bslcuvhgUVCpPS9B3tbT5W8a4GEIIw94djpD1UiIePp8BJGSFnVjGeSiFYq42rW6rgY8UQs+dkYVAH4wRVhiRSt+2WGfWydYbSf4mwGMg+B28rY2T1XFmnttNB8i3BMTrGsXWkg2HuntX2lCg=
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    tags: true

