dist: xenial
language: go
addons:
  apt:
    packages:
    - bsdtar
go:
- '1.13'
git:
  depth: 500
sudo: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
- "./tools/build.sh"
script:
- curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
- unzip awscli-bundle.zip
- "./awscli-bundle/install -b ~/bin/aws"
- "./tools/test.sh"
- "./tools/build_rel_notes.sh"
- "./tools/publish.sh"
after_script:
- tools/notify.sh digitalrebar/provision-plugins
notifications:
  slack:
    secure: Imuptg78FWWZlGVb8LBuwn45CeMfnHgf+pXbftR8mSGFRsg08jw38MIRtw/MAET3RJsciwDXf22AkgM8WgZ+fcUbJI4MGn2IvnM40T/imc5deqlMn1QdE5HasWrrBwfyY7hDu8XBexit+2fmYLGGrHX2fsbvUJepT4xOV8MZbZWMYueoBuL2bxNRR+lhjqVsKMq+/8q4g7hsKxYOdStEOZQIM13qI8dbIIQK4cCPQGtdNMGlNSX0a/nEFZmxDKh3WILssZcRst7SW3QldYppJO21PcTmY/zCTLJ5b7izweLczDmV77ckv61X50B8iaarhwEMFYs9Icg8U69mAkbqeU5HsWy1d2VDPDG+QW32VMTU371pVEzsmBVzArSXvldULmRzYcA+9LoYb5P6LNbq2y7tdimETOElbkMyw53hnb4ZPiypLWlwusZibCxGsJMp41MgbxxaMKxUgrBsAY9nSBg/oj7ixditveXm5IjqBJXfFyxuxfvcxssT15AiqFI3z+Mpoarq233V7E/c0AwdYc/iJKPtW8DG2uSjb0EMIKopXjEi/tz8ykVQH1UbKww5PvGfzCw2mCNF+Bc925coTs8gwaU+XOnqQesggUheAmpaQhbdPGpNYecbLgtQ3kafEBllTrgLyTqISkXlDMZybItP1C8GrEEshGWSEzBAEGU=
env:
  global:
  - secure: LqGvNMznkFjZDWmpms1tSMu/bmPkD0zMUJZXNCj4Mf4nqZP+Ds/JOwu/CWMNyPl+RZskeFiuoaZjQm4cZ4km+5GPl1uPDV/NgTJjoo5FmCDR5cD3sCBeUggom9JG7sksDBI4LFtNHFba+Xc4hIRZzEntFhasnLZcauq8UHYZrMnNvn3ogWJa12ExfqKM5EIbVtuO/g8um4C4dk0qHs+RknjZYzvaBMiDAEK2vTOLDWkyGl/DJWPNu7iEfqG4YktwLn0HP4gdLq9zMBJI9rOEP0/z5yB6yeUUxzS8qhS1IkvgKALKdtUvdpnc9YJRQniqQ8hWvZGTEz+7DBTHdKWF2DDpJqT/km+A4gn2qdf1/oanQ9F5Kv52i25CPH8QEh4fFkvr0H9u3ZV8I1CzY+B2f5y/n4ywD04SGdYm31MDBK2mGeB9Q4Tl/ikjMg/76p6V7p9du8qy5uqcrAft9+SOk6hFw8yGTrXfvl0hltqJYjOcn1oH2CTYuu142JDWLRztIfl3JwPmQlgnNf0xKZVHxq6ObqQGVdlA6AsT7jOf05osnlXF3Ors8l/8NZgPhzKYnoyTBUf5AxgzSEwdOgw2mU5/8to8YZXp0iRzv4d3m/Tm7vcfc4MPMmlOQ8RrcRhTNb9omJm2inJp5YDhS7+Y9awqBlxAi6alIJRWkgyV2T0=
  - secure: WXZLWtgt7WT45jVCAd+u4jCKBf+eQrFsKgPhDFGkuwxNXn8Hnpewq7Ej6ovE5lHIFDsndy0G93e9PT2OklAAepc4JUjPuGC+npEwu8/KftGcp3vbgH1ATo+O/4Y5ALXIY1lNHPkgRGj3PXcR6TqtZvpnI9cHJxh0/GC1igsO9AXMo6Pep2D6VDmuqlEgc1CZSggyepiMQBNAJrS1QCaAJK/PHYlMwSJbzVsg/2BBff9PGgfcLblC/CNFIKCX6/AmiqBp+scurdkJwJ7uEsa8BEuG8FJSnVaiP+kNrVuUugxZ1Y+7G7qMgm7UvWoD92Ezw4CRCWgbGi6gFeHD0cSP2dnN+AbGwtZSf32eW8Kl8a4EwOEYgKDrlQ0XuRnZjR3VlTj1jfZc2l38M+JH3YsvcOPwt4BYOvZTWPUaUYs0zxeUZkl/Tb2vbKQMh2ClrzfbJSPioBteHLgQ/tAZ89WfVjeDYNQqZ7RZYMnD54DUgJJ95lT996Ojp3ObbQVt1e/HjC+6GqdQXOzTWll8nxoktna11gqEJcBMoGeLx7j9eDU5N+ugAZrhnvzuvaSDraoT39Aj6X71gBBxS4lALc4BoZkYt8x2a/g2uBsGbihe1cQ1kC0W/qWkTKygDk3QpEtXg3qXt0BLzkPWoFOJSua6gGiMC/qWmbjxGvW9IUkK1Gg=
  - secure: U3aj3TqcXfiNA5Vi69316xYj6dZeI5A9prclQolS3rRuEI+ZKFUftwqzQRKVG+caVLwLH5GPj2ixIOKQ0rJs+FJTOEXYEVqMxpNRNzBSgdO5Ehr4actG4axnkSHARnfIYeJgHQwFufDmuW7sMv+ZCk64zDsF13ZC7g7u881AgDOF4yfhSs2JRsRPj90PBcKPcEw2UnYYkgmU3W6u4MV9qJel5ZbypbYKGwgASXzm/eYVKJYmz7b6x601ztJFdyIBP6mGf/G/Hl99xxTTYvY7dXO3kNIC2eq/gYWyJq8Lqg+mknU4uTB4e9+3yTJvs0L1Tfgg7BwkY8bcSN18/6kVOvF6L5T/VagQ5BI6hulWLvVfYyjPsXt4sMnqz4oZ+QTbKtFH+Ie4xtquc/Mu+qSRxicS1eGZdhswvWuVyjmxPPfw2rKWNtYfbvmOj+RnZSb6vTcqcBDwZv28PNGR4VEDhNRBXdX4t89mVYvyTbeCpPtKCMWzSNASLYM681PfVz+LBfM53yiGeOU3JQLogutyzscnYAJkGfTG0KN5Ti6X9eaz9ihJR+Z2G+QVjIqljS5mvcrX2+/c2okGIzPAr8ogFXZW9w9DVp9MIY1ErQ20Y6yb4ASAUdotYomRsX/EzFudSH9TB92TM4C7kJESuXqH46ZAfgNW0ockCJhDpAsjx4k=
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    branch: v4
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: rebar-catalog
  region: us-west-2
  local-dir: rebar-catalog
  acl: public_read
  skip_cleanup: true
  on:
    repo: digitalrebar/provision-plugins
    tags: true
