---
Name: "cloud-init/x509-certs"
Description: "The cloud init x509 certs"
Documentation: |
  This contains all the x509 certs for the system as a single string
Schema:
  type: "string"
Meta:
  icon: "map"
  color: "blue"
  title: "RackN Content"
