---
Name: "image-deploy/skip-grub2-configure"
Description: "Whether to skip trying to reconfigure grub.  Should be set to true if you are using a raw image"
Schema:
  type: boolean
  default: false
Meta:
  icon: "beer"
  color: "yellow"
  title: "RackN Content"
