---
Name: "esxi-preserve-logs"
Description: "Preserve the logs to a datastore area"
Documentation: |
  Preserve the logs to a datastore area.
Meta:
  icon: "cloud"
  color: "yellow"
  title: "Digital Rebar"
Templates:
  - Name: "esxi-preserve-logs.sh"
    Contents: |
      #!/usr/bin/env sh
      {{ if eq (.Param "rs-debug-enable") true }}set -x{{ end }}
      # Generate a new scratch directory for this host on a Datastore
      DS=$(localcli --formatter json storage filesystem list|python -c "import sys,json;x=json.load(sys.stdin);y=[i for i in x if i['Type']=='VFFS' or 'vmfs' in i['Type'].lower()];print(y[0]['Mount Point'])")
      scratchdirectory=$DS/locker
      # Create the scratch directory
      mkdir -p $scratchdirectory
      # Change the advanced configuration option
      vim-cmd hostsvc/advopt/update ScratchConfig.ConfiguredScratchLocation string $scratchdirectory
      # saves a copy of the install logs to permanent storage from /scratch
      echo "$(date)" >  /tmp/esxi-preserve-logs-template-run-stamp
      LOG_DIR="${DS}/install-logs/"

      mkdir -p $LOG_DIR \
        && cp -Lfr /var/log/* $LOG_DIR \
        || echo "failed to 'mkdir -p $LOG_DIR'"

      # save some other weasel/installer files
      ONE="/tmp/onetime/var/lib/vmware/firstboot"
      KS="/tmp/kickstart-customizations.cfg"
      JUMP="/tmp/jumpstrt.gz"
      for FILE in "$ONE" "$KS" "$JUMP"
      do
        [[ -f "$FILE" ]] && cp -r "$FILE" "$LOG_DIR"
      done

      exit 0
