---
Name: "esxi-install-startup-agent"
Description: "Install DRPY as an agent at startup"
Documentation: |
  This task will install DRPY into the local.sh for startup.

Meta:
  icon: "cloud"
  color: "yellow"
  title: "Digital Rebar"
Templates:
  - Name: "esxi-install-agent.sh"
    Contents: |
      #!/usr/bin/env sh
      # ensure DRPY is set to start on boot of ESXi instance - this needs help - lots

      ###
      #  use the local.sh script to fire up DRPY on boot
      #
      #  this desperately needs better integration
      #
      #  DRP-Agent.vib must have been installed previously
      ###

      {{ if eq (.Param "esxi/drpy-agent-enable") true -}}
      echo "Setting DRPY Agent to start at ESXi boot time."
      {{ else -}}
      # DRPY Agent set to not start at boot time by 'esxi/drpy-agent-enable' Param false
      exit 0
      {{ end -}}

      function xiterr() { [[ "$1" =~ ^[0-9]+$ ]] && { XIT=$1; shift; } || XIT=1; printf "FATAL: $*\n"; exit $XIT; }
      RB="/opt/rackn/drpy"
      RA="$RB/agent"
      RD="$RB/bin"
      RP="$RD/esxi-drp-run.py"
      RC="/etc/rc.local.d/local.sh"

      [[ ! -d "$RB" ]] && xiterr "No '$RB' path - appears DRPY wasn't installed yet."

      if $( grep -qe "^# Start up the DRPY agent on an ESXi system." $RC )
      then
        echo "DRPY execution in $RC already.  Nothing done."
      else
        head -n -1 $RC > /tmp/jj
        cat >> /tmp/jj <<EOF
      mkdir -p $RD
      cat >> $RP <<INSIDEEOF
      {{template "esxi-drpy-run.py.tmpl" .}}
      INSIDEEOF
      chmod +x $RP
      /bin/nohup $RP &
      exit 0
      EOF
        cp /tmp/jj $RC

        $(grep -qe "^# Start up the DRPY agent on an ESXi system." $RC) && echo "Startup tool ('$TOOL') installed successfully" || xiterr "Failed to install '$TOOL'"
      fi
      exit 0
