---
Name: "esxi-set-dns"
Description: "Setup DNS components in ESXi"
Documentation: |
  Setup DNS components in ESXi, using the params:

    * ``dns-servers``
    * ``dns-domain``
    * ``dns-search-domains``

Meta:
  icon: "cloud"
  color: "yellow"
  title: "Digital Rebar"
Templates:
  - Name: "esxi-set-dns.sh"
    ID: "esxi-set-dns.sh.tmpl"
