---
Name: "esxi-set-patch-list"
Description: "A task to set the patch list for ESXi instance during firstboot."
Documentation: ""
Meta:
  color: "yellow"
  feature-flags: "sane-exit-codes"
  icon: "cloud"
  title: "RackN"
Templates:
  - Name: "ESXi Patch"
    Path: ""
    ID: "esxi-set-patch-list.sh.tmpl"
    Contents: ""
