---
Name: "validation-machine-name-dns-to-ip"
Description: "Using the Machine.Name  validate that the esxi/firstboot-ipaddr is what DNS returns."
Documentation: |
  Validates that the machines IP address exists in DNS records.

Meta:
  icon: "money"
  color: "grey"
  title: "RackN Content"
OptionalParams:
  - "esxi/firstboot-ipaddr"
Templates:
  - Name: "check-dns-by-ip.sh"
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl" . }}
      {{ template "validation-lib.tmpl" . }}

      {{ if eq (.ParamExists "esxi/network-firstboot-ipaddr") false }}
      echo "esxi/network-firstboot-ipaddr is not specified"
      exit 1
      {{ end }}
      if ! validate_machine_name_dns_by_ip {{.Param "esxi/network-firstboot-ipaddr"}} ; then
          echo "DNS validation failed."
          exit 1
      fi
      echo "DNS validation succeeded."
      exit 0
