---
Name: "vmware-vsan-hcl-validate"
Description: "A task to validate VSAN HCL compliance"
Documentation: |
  This task will verify that the Machine is HCL compliant for
  VSAN installation.

Meta:
  color: "blue"
  feature-flags: "sane-exit-codes"
  icon: "search"
  title: "RackN"
Templates:
- Contents: ""
  ID: "vmware-vsan-hcl-validate.sh.tmpl"
  Name: "VMware VSAN HCL Validator"
  Path: ""
