---
Name: "curtin-deploy"
Description: "A task to install an image through curtin."
OptionalParams:
- "image-deploy/windows-license-key"
- "curtin/partitions"
- "image-deploy/image-file"
- "image-deploy/image-url"
RequiredParams:
- "image-deploy/image-type"
- "image-deploy/image-os"
Templates:
- ID: "curtin-config.yaml.tmpl"
  Name: "The base curtin config file"
  Path: "curtin_config.yaml"
- ID: "curtin-config.yaml.tmpl"
  Name: "The base curtin config file in root"
  Path: "/root/curtin_config.yaml"
- ID: "curtin-windows-maasservice.py.tmpl"
  Path: "windows/maasservice.py"
  Name: "Hack on Cloudbase Init"
- ID: "curtin-linux-curtin-hooks.py.tmpl"
  Path: "linux/curtin-hooks.py"
  Name: "Linux curtin-hooks.py"
- ID: "curtin-linux-finalize.py.tmpl"
  Path: "linux/finalize.py"
  Name: "Linux finalize.py"
- ID: "curtin-linux-python_wrapper.tmpl"
  Path: "linux/python_wrapper"
  Name: "Linux python_wrapper"
- ID: "curtin-linux-finish.sh.tmpl"
  Path: "linux/drpcli.sh"
  Name: "Linux drpcli.sh"
- ID: "curtin-windows-curtin-hooks.tmpl"
  Path: "windows/curtin-hooks"
  Name: "Windows curtin-hooks"
- ID: "curtin-windows-finalize.py.tmpl"
  Path: "windows/finalize.py"
  Name: "Windows finalize.py"
- ID: "curtin-windows-finalize.tmpl"
  Path: "windows/finalize"
  Name: "Windows finalize"
- ID: "curtin-windows-finish.ps1.tmpl"
  Path: "windows/drpcli.ps1"
  Name: "Windows drpcli.ps1"
- ID: "curtin-basic-curtin-hooks.tmpl"
  Path: "basic/curtin-hooks"
  Name: "Basic curtin-hooks"
- ID: "curtin-basic-finalize.tmpl"
  Path: "basic/finalize"
  Name: "Basic finalize"
- ID: "curtin-basic-windows-finish.ps1.tmpl"
  Path: "basic/drpcli.ps1"
  Name: "Basic drpcli.ps1"
- ID: "curtin-basic-linux-finish.sh.tmpl"
  Path: "basic/drpcli.sh"
  Name: "Basic drpcli.sh"
- ID: "curtin-install.sh.tmpl"
  Name: "Install an image with curtin"
  Path: ""
Meta:
  icon: "image"
  color: "blue"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
