---
Name: "bios-current-config"
Description: "Get current BIOS configuration for the system"
Documentation: |
  This task populates the ``bios-current-configuration`` parameter on the machine
  it runs on with a dump on the current configuration settings.  Depending on
  what the underlying ``bios-driver`` supports, this may include various read-only
  settings, additional documentation on each setting, and allowable types and ranges
  that values can take.  As such, the format of the ``bios-current-configuration`` parameter
  is deliberatly left undefined.

  This task is not required for correct operation of the system -- it is present for informational
  purposes only.
RequiredParams:
  - bios-driver
Prerequisites:
  - bios-tools-install
Meta:
  icon: "setting"
  color: "blue"
  title: "RackN Content"
Templates:
  - Name: "current-config"
    Contents: |
      #!/usr/bin/env bash
      {{ template "setup.tmpl" . }}
      if [[ {{.Param "bios-driver"}} = "lenovo" ]]; then
          {{ if .ParamExists "lenovo-onecli-install-target" }}
          export PATH="$PATH:{{.Param "lenovo-onecli-install-target"}}"
          {{ else }}
          echo "Please install the lenovo-support content package"
          exit 1
          {{ end }}
      fi
      drpcli machines remove {{.Machine.UUID}} param bios-current-configuration || :
      drp-bioscfg -driver {{.Param "bios-driver"}} |drpcli machines set {{.Machine.UUID}} param bios-current-configuration to -
