---
Name: passgen-settings
Description: Sets the format options for random password strings.
Documentation: |

  This string sets values that are used to control the format random
  generated strings by the ``passgen.py.tmpl`` template.  This is usually
  used to generate a random password string with a given set of rules.

  Some notes about the rules:

    * ``chars`` can not be less than the sum of ``upper`` + ``lower`` + ``special_chars`` + ``req_nums``)
    * The ``padding`` value type will "fill out" (i.e. pad) the password with characters of the specified type, if not enough chars are generated to fill the full ``length``
    * Allowed values for ``padding`` are:
      + lowers
      + uppers
      + nums
    * Default set of special characters is set to VMware "safe" values of:
      + [!%@$^]
    * You can override the ``special_char_list`` - however, you must be aware of the processing pipeline, as some special characters will cause Workflow errors when trying to marshal from JSON to YAML, etc.
    * You only need to override a given value to make a change to it, all remaning values not specified will use the below defaults

  The default settings are as follows:

    length=10, chars=7, req_nums=2, special_chars=1,
    special_char_list=None, upper=2, lower=5, padding=None

  EXAMPLES:

  To set custom values for ``passgen.py.tmpl`; create a Param named
  "passgen-settings", add it to a Machine Object (via ``global`` profile,
  a custom profile applied to the given Machine, or a Param directly
  applied to the Machine), with the values set as below.

    Setting the length to 14 chars, all other values to default:

      ::

        length=14

    Set length to 12, and the list of special characters that can be used:

      ::

        length=12, special_char_list='!%@$^;,_'

    To change the special characters to always generate 3 special characters,
    instead of the default of only 1, do:

      ::

        special_chars=2

  ..note:: You must put commas between multiple settings values.

Meta:
  color: blue
  icon: hashtag
  title: RackN Content
ReadOnly: true
Schema:
  type: string
  default: "length=10, chars=7, req_nums=2, special_chars=1, special_char_list=None, upper=2, lower=5, padding=None"
Secure: false
