---
Name: raid-inventory
Description: Inventory current RAID volumes on the system
Documentation: |
  This task records the current RAID configuration on the machine's object
  in the `raid-current-config` parameter.
Prerequisites:
  - raid-tools-install
Meta:
  icon: "disk outline"
  color: "blue"
  title: "RackN Content"
Templates:
  - Name: raid-inventory
    Contents: |
      #!/usr/bin/env bash
      {{template "setup.tmpl" .}}
      echo "Gathering configuration:"
      drp-raid | drpcli machines set {{.Machine.UUID}} param raid-current-config to -

