---
Name: raid-set-baseline
Description: Inventory current RAID volumes on the system as set them as target configuration
Prerequisites:
  - raid-tools-install
Meta:
  icon: "disk outline"
  color: "blue"
  title: "RackN Content"
Templates:
  - Name: raid-set-baseline
    Contents: |
      #!/usr/bin/env bash
      {{template "setup.tmpl" .}}
      echo "Gathering configuration:"
      drp-raid -volspecs | drpcli machines set {{.Machine.UUID}} param raid-target-config to -
