---
Name: raid-configure-example
Description: Configure wanted RAID volumes on the system
Documentation: |
  Deprecated Task to configure the RAID Subsystem.

  This is replaced by `raid-configure`.
Prerequisites:
  - raid-tools-install
Meta:
  icon: "disk outline"
  color: "blue"
  title: "RackN Content"
RequiredParams:
  - raid-target-config
  - raid-skip-config
  - raid-clear-config
Templates:
  - Name: raid-configure
    Contents: |
      #!/usr/bin/env bash
      {{template "setup.tmpl" .}}
      if [[ {{.Param "raid-skip-config"}} == true ]]; then
          echo "Skipping RAID config"
          exit 0
      fi
      if [[ {{.Param "raid-clear-config"}} == true ]]; then
          (drp-raid -tools "{{.Param "raid-usable-utilities" | join ","}}" -clear) || exit 1
      fi
      echo "Building this configuration:"
      (echo '{{.ParamAsJSON "raid-target-config"}}' | drp-raid -tools "{{.Param "raid-usable-utilities" | join ","}}" -compile)
      (echo '{{.ParamAsJSON "raid-target-config"}}' | drp-raid -tools "{{.Param "raid-usable-utilities" | join ","}}" -configure) || exit 1
      drp-raid -tools "{{.Param "raid-usable-utilities" | join ","}}" | drpcli machines set {{.Machine.UUID}} param raid-current-config to -
      drpcli machines set "$RS_UUID" param raid-skip-config to true

