---
Name: bios-configure-example
Description: "Discover and update BIOS configurations on a system"
BootEnv: sledgehammer
Tasks:
  - bios-current-config
  - bios-configure
  - bios-ilo-configuration
Meta:
  icon: "setting"
  color: "yellow"
  title: "RackN Content"
