---
Name: bios-idrac-pre-configuration
Description: "The IDRAC configuration files to apply to the system before bios-configure"
Documentation: |
  This is currently unspecified.

  These are run before bios-configure.
Meta:
  color: grey
  icon: money
Schema:
  type: array
  default: []
  items:
    type: string
