---
Name: bios-lenovo-pre-configuration
Description: "The Lenovo batch configuration files to apply to the system before bios-configure"
Documentation: |
  This is a list of strings (to be files) to apply to the system through onecli in batch mode.

  If a line contains --file=<file> or --file <file>, the system will attempt to make sure that file is
  present and, if not present, retrieve it from the `bios-file-base-url` location.  Paths are maintained.

  These are applied before bios-configure.
Meta:
  color: grey
  icon: money
Schema:
  type: array
  default: []
  items:
    type: string
