---
Name: bios-idrac-configuration
Description: "The IDRAC configuration files to apply to the system"
Documentation: |
  This is currently unspecified.

Meta:
  color: grey
  icon: money
Schema:
  type: array
  default: []
  items:
    type: string
