---
Name: "ipmi-network-validation"
Description: Validate the network settings for ipmi
Meta:
  icon: "server"
  color: "blue"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
OptionalParams:
  - "ipmi/configure/address"
  - "ipmi/configure/gateway"
  - "ipmi/configure/netmask"
Templates:
  - Name: "validate-ipmi-network.sh"
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl" . }}
      {{ template "validation-lib.tmpl" . }}

      ERR=0
      {{ if eq (.ParamExists "ipmi/configure/address") false }}
            echo "ipmi/configure/address is not specified"
            ERR=1
      {{ else }}
      IP={{ .Param "ipmi/configure/address" }}
      {{ end }}

      {{ if eq (.ParamExists "ipmi/configure/gateway") false }}
            echo "ipmi/configure/gateway is not specified"
            ERR=1
      {{ else }}
      GW={{ .Param "ipmi/configure/gateway" }}
      {{ end }}

      {{ if eq (.ParamExists "ipmi/configure/netmask") false }}
            echo "ipmi/configure/netmask is not specified"
            ERR=1
      {{ else }}
      NM={{ .Param "ipmi/configure/netmask" }}
      {{ end }}

      if [[ $ERR == 1 ]] ; then
          exit 1
      fi

      echo "IP Addr (ipmi/configure/address) = ${IP}"
      echo "Gateway (ipmi/configure/gateway) = ${GW}"
      echo "Netmask (ipmi/configure/netmask) = ${NM}"
      if check_same_subnet ${IP} ${GW} ${NM} ; then
          echo "IPMI Configure Network Validation Success"
          exit 0
      else
          echo "IPMI Configure Network Validation Failure"
          echo "IP Address and Gateway are not in the same network."
          exit 1
      fi
